#!/usr/bin/env bash
set -e
DB_NAME=testdb
DB_USER=testuser


# Ensure CSVs are present (generated by seed_generate.py)
python3 sql/seed_generate.py


# Load customers
psql -d $DB_NAME -c "\copy demo.customers(id,name,email,created_at) FROM 'sql/customers.csv' CSV HEADER;"
# Load orders
psql -d $DB_NAME -c "\copy demo.orders(id,customer_id,amount,status,created_at) FROM 'sql/orders.csv' CSV HEADER;"


echo "Data loaded."